name: Flask CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
        
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -m unittest discover tests 

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}        
    
    - name: Build Docker image
      run: |
        docker build -t flask-app:latest .
        docker tag flask-app:latest ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
    
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
        
    - name: Run Docker container
      run: |
         docker run -d -p 5000:5000 --name flask-app-container ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
    
    - name: Check Docker container logs
      run: |
        sleep 5 # Give the container some time to start
        docker logs flask-app-container    
    
    - name: Test application
      run: |
        sleep 10 # Give the container some time to start
        curl http://localhost:5000
        
    - name: Stop and remove container
      run: |
        docker stop flask-app-container
        docker rm flask-app-container

